### ISSUE TITLE
Module not found: Error: Can't resolve 'react' in non-react environnements(Vue/Node)

### ISSUE THREAD

**Issue by victorgarciaesgi** [xoredg/apollo-link-logger#60]
I have this error when compiling my Vue app with `@apollo/client` v3, and latest version from `apollo-link-logger`

The error comes from here, where you are importing from the entire @apollo/client package, and importing react;

https://github.com/blackxored/apollo-link-logger/blob/73806916280054f6844ce1cc59b21f75b38ea542/src/index.js#L2

Possible fix comes from their [docs](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#using-apollo-client-without-react)

```ts
import { ApolloLink } from '@apollo/client/core';
```

**Comment by chegger** [comment]
Having the same problem here. Although I've been using t he `apollo-link-logger` and a similar apollo link (`aws-appsync-auth-link`) for a couple of months now, this is somehow breaking just now. In fact, when I look at the history of our ci/cd, it  turns out that the `apollo-link-logger` were still working only ~10 hours ago.

I wonder why this is the case. @victorgarciaesgi's should do the trick, IMO. Using the `@apollo/client/core` module the exact same way in places of our codebase where `react` is not present.

@blackxored what do you think? I'd be happy to do an MR for this one, as I think it will make the package more compatible again!

**Comment by chegger** [comment]
Also note, a **clean and simple fix** is actually just installing `react` via `npm i react`.

I was worried about using it as I thought `react` to be a large package, but a quick glance over to bundlephobia shows that it is just `7kB` minified and `2.8kB` minified + gzipped
https://bundlephobia.com/result?p=react@17.0.2

**Comment by DavidMusijenko** [comment]
I made a package with your solution if anyone needs it:
https://www.npmjs.com/package/apollo-link-logger-no-react
